import 'package:shishu_sanskar/utils/constant/app_image.dart';

final List<Map<String, String>> countryList = [
  {"code": "AD", "name": "Andorra", "dial_code": "+376", "flag": AppFlag.ad},
  {
    "code": "AE",
    "name": "United Arab Emirates",
    "dial_code": "+971",
    "flag": AppFlag.ae,
  },
  {"code": "AF", "name": "Afghanistan", "dial_code": "+93", "flag": AppFlag.af},
  {
    "code": "AG",
    "name": "Antigua and Barbuda",
    "dial_code": "+1-268",
    "flag": AppFlag.ag,
  },
  {"code": "AI", "name": "Anguilla", "dial_code": "+1-264", "flag": AppFlag.ai},
  {"code": "AL", "name": "Albania", "dial_code": "+355", "flag": AppFlag.al},
  {"code": "AM", "name": "Armenia", "dial_code": "+374", "flag": AppFlag.am},
  {"code": "AO", "name": "Angola", "dial_code": "+244", "flag": AppFlag.ao},
  {"code": "AQ", "name": "Antarctica", "dial_code": "+672", "flag": AppFlag.aq},
  {"code": "AR", "name": "Argentina", "dial_code": "+54", "flag": AppFlag.ar},
  {
    "code": "AS",
    "name": "American Samoa",
    "dial_code": "+1-684",
    "flag": AppFlag.as,
  },
  {"code": "AT", "name": "Austria", "dial_code": "+43", "flag": AppFlag.at},
  {"code": "AU", "name": "Australia", "dial_code": "+61", "flag": AppFlag.au},
  {"code": "AW", "name": "Aruba", "dial_code": "+297", "flag": AppFlag.aw},
  {
    "code": "AX",
    "name": "Åland Islands",
    "dial_code": "+358",
    "flag": AppFlag.ax,
  },

  {"code": "AZ", "name": "Azerbaijan", "dial_code": "+994", "flag": AppFlag.az},
  {
    "code": "BA",
    "name": "Bosnia and Herzegovina",
    "dial_code": "+387",
    "flag": AppFlag.ba,
  },
  {"code": "BB", "name": "Barbados", "dial_code": "+1-246", "flag": AppFlag.bb},
  {"code": "BD", "name": "Bangladesh", "dial_code": "+880", "flag": AppFlag.bd},
  {"code": "BE", "name": "Belgium", "dial_code": "+32", "flag": AppFlag.be},
  {
    "code": "BF",
    "name": "Burkina Faso",
    "dial_code": "+226",
    "flag": AppFlag.bf,
  },
  {"code": "BG", "name": "Bulgaria", "dial_code": "+359", "flag": AppFlag.bg},
  {"code": "BH", "name": "Bahrain", "dial_code": "+973", "flag": AppFlag.bh},
  {"code": "BI", "name": "Burundi", "dial_code": "+257", "flag": AppFlag.bi},
  {"code": "BJ", "name": "Benin", "dial_code": "+229", "flag": AppFlag.bj},
  {
    "code": "BL",
    "name": "Saint Barthélemy",
    "dial_code": "+590",
    "flag": AppFlag.bl,
  },
  {"code": "BM", "name": "Bermuda", "dial_code": "+1-441", "flag": AppFlag.bm},

  {
    "code": "BO",
    "name": "Bolivia, Plurinational State of",
    "dial_code": "+591",
    "flag": AppFlag.bo,
  },
  {
    "code": "BQ",
    "name": "Caribbean Netherlands",
    "dial_code": "+599",
    "flag": AppFlag.bq,
  },
  {"code": "BR", "name": "Brazil", "dial_code": "+55", "flag": AppFlag.br},
  {"code": "BS", "name": "Bahamas", "dial_code": "+1-242", "flag": AppFlag.bs},
  {"code": "BT", "name": "Bhutan", "dial_code": "+975", "flag": AppFlag.bt},

  {"code": "BW", "name": "Botswana", "dial_code": "+267", "flag": AppFlag.bw},
  {"code": "BY", "name": "Belarus", "dial_code": "+375", "flag": AppFlag.by},
  {"code": "BZ", "name": "Belize", "dial_code": "+501", "flag": AppFlag.bz},
  {"code": "CA", "name": "Canada", "dial_code": "+1", "flag": AppFlag.ca},
  {
    "code": "CC",
    "name": "Cocos (Keeling) Islands",
    "dial_code": "+61",
    "flag": AppFlag.cc,
  },
  {
    "code": "CD",
    "name": "Congo, the Democratic Republic of",
    "dial_code": "+243",
    "flag": AppFlag.cd,
  },
  {
    "code": "CF",
    "name": "Central African Republic",
    "dial_code": "+236",
    "flag": AppFlag.cf,
  },
  {
    "code": "CG",
    "name": "Republic of the Congo",
    "dial_code": "+242",
    "flag": AppFlag.cg,
  },
  {"code": "CH", "name": "Switzerland", "dial_code": "+41", "flag": AppFlag.ch},
  {
    "code": "CI",
    "name": "Côte d'Ivoire",
    "dial_code": "+225",
    "flag": AppFlag.ci,
  },
  {
    "code": "CK",
    "name": "Cook Islands",
    "dial_code": "+682",
    "flag": AppFlag.ck,
  },
  {"code": "CL", "name": "Chile", "dial_code": "+56", "flag": AppFlag.cl},
  {"code": "CM", "name": "Cameroon", "dial_code": "+237", "flag": AppFlag.cm},
  {
    "code": "CN",
    "name": "China (People's Republic of China)",
    "dial_code": "+86",
    "flag": AppFlag.cn,
  },
  {"code": "CO", "name": "Colombia", "dial_code": "+57", "flag": AppFlag.co},
  {"code": "CR", "name": "Costa Rica", "dial_code": "+506", "flag": AppFlag.cr},
  {"code": "CU", "name": "Cuba", "dial_code": "+53", "flag": AppFlag.cu},
  {"code": "CV", "name": "Cape Verde", "dial_code": "+238", "flag": AppFlag.cv},
  {"code": "CW", "name": "Curaçao", "dial_code": "+599", "flag": AppFlag.cw},
  {
    "code": "CX",
    "name": "Christmas Island",
    "dial_code": "+61",
    "flag": AppFlag.cx,
  },
  {"code": "CY", "name": "Cyprus", "dial_code": "+357", "flag": AppFlag.cy},
  {
    "code": "CZ",
    "name": "Czech Republic",
    "dial_code": "+420",
    "flag": AppFlag.cz,
  },
  {"code": "DE", "name": "Germany", "dial_code": "+49", "flag": AppFlag.de},
  {"code": "DJ", "name": "Djibouti", "dial_code": "+253", "flag": AppFlag.dj},
  {"code": "DK", "name": "Denmark", "dial_code": "+45", "flag": AppFlag.dk},
  {"code": "DM", "name": "Dominica", "dial_code": "+1-767", "flag": AppFlag.dm},

  {
    "code": "DO",
    "name": "Dominican Republic",
    "dial_code": "+1-809",
    'flag': AppFlag.doo,
  },
  {"code": "DZ", "name": "Algeria", "dial_code": "+213", 'flag': AppFlag.dz},
  {"code": "EC", "name": "Ecuador", "dial_code": "+593", 'flag': AppFlag.ec},
  {"code": "EE", "name": "Estonia", "dial_code": "+372", 'flag': AppFlag.ee},
  {"code": "EG", "name": "Egypt", "dial_code": "+20", 'flag': AppFlag.eg},
  {
    "code": "EH",
    "name": "Western Sahara",
    "dial_code": "+212",
    'flag': AppFlag.eh,
  },
  {"code": "ER", "name": "Eritrea", "dial_code": "+291", 'flag': AppFlag.er},
  {"code": "ES", "name": "Spain", "dial_code": "+34", 'flag': AppFlag.es},
  {"code": "ET", "name": "Ethiopia", "dial_code": "+251", 'flag': AppFlag.et},
  {"code": "EU", "name": "Europe", "dial_code": "+39", 'flag': AppFlag.eu},
  {"code": "FI", "name": "Finland", "dial_code": "+358", 'flag': AppFlag.fi},
  {"code": "FJ", "name": "Fiji", "dial_code": "+679", 'flag': AppFlag.fj},
  {
    "code": "FK",
    "name": "Falkland Islands (Malvinas)",
    "dial_code": "+500",
    'flag': AppFlag.fk,
  },
  {
    "code": "FM",
    "name": "Micronesia, Federated States of",
    "dial_code": "+691",
    'flag': AppFlag.fm,
  },
  {
    "code": "FO",
    "name": "Faroe Islands",
    "dial_code": "+298",
    'flag': AppFlag.fo,
  },
  {"code": "FR", "name": "France", "dial_code": "+33", 'flag': AppFlag.fr},
  {
    "code": "GB-ENG",
    "name": "England",
    "dial_code": "+44",
    'flag': AppFlag.gbEng,
  },
  {
    "code": "GB-NIR",
    "name": "Northern Ireland",
    "dial_code": "+44",
    'flag': AppFlag.gbNir,
  },
  {
    "code": "GB-SCT",
    "name": "Scotland",
    "dial_code": "+44",
    'flag': AppFlag.gbSct,
  },
  {
    "code": "GB-WLS",
    "name": "Wales",
    "dial_code": "+44",
    'flag': AppFlag.gbWls,
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "dial_code": "+44",
    'flag': AppFlag.gb,
  },
  {"code": "GD", "name": "Grenada", "dial_code": "+1-473", 'flag': AppFlag.gd},
  {"code": "GE", "name": "Georgia", "dial_code": "+995", 'flag': AppFlag.ge},
  {
    "code": "GF",
    "name": "French Guiana",
    "dial_code": "+594",
    'flag': AppFlag.gf,
  },
  {"code": "GG", "name": "Guernsey", "dial_code": "+44", 'flag': AppFlag.gg},
  {"code": "GH", "name": "Ghana", "dial_code": "+233", 'flag': AppFlag.gh},
  {"code": "GI", "name": "Gibraltar", "dial_code": "+350", 'flag': AppFlag.gi},
  {"code": "GL", "name": "Greenland", "dial_code": "+299", 'flag': AppFlag.gl},
  {"code": "GM", "name": "Gambia", "dial_code": "+220", 'flag': AppFlag.gm},
  {"code": "GN", "name": "Guinea", "dial_code": "+224", 'flag': AppFlag.gn},
  {"code": "GP", "name": "Guadeloupe", "dial_code": "+590", 'flag': AppFlag.gp},
  {
    "code": "GQ",
    "name": "Equatorial Guinea",
    "dial_code": "+240",
    'flag': AppFlag.gq,
  },
  {"code": "GR", "name": "Greece", "dial_code": "+30", 'flag': AppFlag.gr},
  {
    "code": "GS",
    "name": "South Georgia and the South Sandwich Islands",
    "dial_code": "+500",
    'flag': AppFlag.gs,
  },
  {"code": "GT", "name": "Guatemala", "dial_code": "+502", 'flag': AppFlag.gt},
  {"code": "GU", "name": "Guam", "dial_code": "+1-671", 'flag': AppFlag.gu},
  {
    "code": "GW",
    "name": "Guinea-Bissau",
    "dial_code": "+245",
    'flag': AppFlag.gw,
  },
  {"code": "GY", "name": "Guyana", "dial_code": "+592", 'flag': AppFlag.gy},
  {"code": "HK", "name": "Hong Kong", "dial_code": "+852", 'flag': AppFlag.hk},
  {
    "code": "HM",
    "name": "Heard Island and McDonald Islands",
    "dial_code": "+61",
    'flag': AppFlag.hm,
  },
  {"code": "HN", "name": "Honduras", "dial_code": "+504", 'flag': AppFlag.hn},
  {"code": "HR", "name": "Croatia", "dial_code": "+385", 'flag': AppFlag.hr},
  {"code": "HT", "name": "Haiti", "dial_code": "+509", 'flag': AppFlag.ht},
  {"code": "HU", "name": "Hungary", "dial_code": "+36", 'flag': AppFlag.hu},
  {"code": "ID", "name": "Indonesia", "dial_code": "+62", 'flag': AppFlag.id},
  {"code": "IE", "name": "Ireland", "dial_code": "+353", 'flag': AppFlag.ie},
  {"code": "IM", "name": "Isle of Man", "dial_code": "+44", 'flag': AppFlag.im},
  {"code": "IN", "name": "India", "dial_code": "+91", 'flag': AppFlag.inn},
  {
    "code": "IO",
    "name": "British Indian Ocean Territory",
    "dial_code": "+246",
    'flag': AppFlag.io,
  },
  {"code": "IQ", "name": "Iraq", "dial_code": "+964", 'flag': AppFlag.iq},
  {
    "code": "IR",
    "name": "Iran, Islamic Republic of",
    "dial_code": "+98",
    'flag': AppFlag.ir,
  },
  {"code": "IS", "name": "Iceland", "dial_code": "+354", 'flag': AppFlag.iss},
  {"code": "IT", "name": "Italy", "dial_code": "+39", 'flag': AppFlag.it},
  {"code": "JE", "name": "Jersey", "dial_code": "+44", 'flag': AppFlag.je},
  {"code": "JM", "name": "Jamaica", "dial_code": "+1-876", 'flag': AppFlag.jm},
  {"code": "JP", "name": "Japan", "dial_code": "+81", 'flag': AppFlag.jp},
  {"code": "KE", "name": "Kenya", "dial_code": "+254", 'flag': AppFlag.ke},
  {"code": "KG", "name": "Kyrgyzstan", "dial_code": "+996", 'flag': AppFlag.kg},
  {"code": "KH", "name": "Cambodia", "dial_code": "+855", 'flag': AppFlag.kh},
  {"code": "KI", "name": "Kiribati", "dial_code": "+686", "flag": AppFlag.ki},
  {"code": "KM", "name": "Comoros", "dial_code": "+269", "flag": AppFlag.km},
  {
    "code": "KN",
    "name": "Saint Kitts and Nevis",
    "dial_code": "+1-869",
    "flag": AppFlag.kn,
  },
  {
    "code": "KP",
    "name": "Korea, Democratic People's Republic of",
    "dial_code": "+850",
    "flag": AppFlag.kp,
  },
  {
    "code": "KR",
    "name": "Korea, Republic of",
    "dial_code": "+82",
    "flag": AppFlag.kr,
  },
  {"code": "KW", "name": "Kuwait", "dial_code": "+965", "flag": AppFlag.kw},
  {
    "code": "KY",
    "name": "Cayman Islands",
    "dial_code": "+1-345",
    "flag": AppFlag.ky,
  },
  {"code": "KZ", "name": "Kazakhstan", "dial_code": "+7", "flag": AppFlag.kz},
  {
    "code": "LA",
    "name": "Laos (Lao People's Democratic Republic)",
    "dial_code": "+856",
    "flag": AppFlag.la,
  },
  {"code": "LB", "name": "Lebanon", "dial_code": "+961", "flag": AppFlag.lb},
  {
    "code": "LC",
    "name": "Saint Lucia",
    "dial_code": "+1-758",
    "flag": AppFlag.lc,
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "dial_code": "+423",
    "flag": AppFlag.li,
  },
  {"code": "LK", "name": "Sri Lanka", "dial_code": "+94", "flag": AppFlag.lk},
  {"code": "LR", "name": "Liberia", "dial_code": "+231", "flag": AppFlag.lr},
  {"code": "LS", "name": "Lesotho", "dial_code": "+266", "flag": AppFlag.ls},
  {"code": "LT", "name": "Lithuania", "dial_code": "+370", "flag": AppFlag.lt},
  {"code": "LU", "name": "Luxembourg", "dial_code": "+352", "flag": AppFlag.lu},
  {"code": "LV", "name": "Latvia", "dial_code": "+371", "flag": AppFlag.lv},
  {"code": "LY", "name": "Libya", "dial_code": "+218", "flag": AppFlag.ly},
  {"code": "MA", "name": "Morocco", "dial_code": "+212", "flag": AppFlag.ma},
  {"code": "MC", "name": "Monaco", "dial_code": "+377", "flag": AppFlag.mc},
  {
    "code": "MD",
    "name": "Moldova, Republic of",
    "dial_code": "+373",
    "flag": AppFlag.md,
  },
  {"code": "ME", "name": "Montenegro", "dial_code": "+382", "flag": AppFlag.me},
  {
    "code": "MF",
    "name": "Saint Martin",
    "dial_code": "+590",
    "flag": AppFlag.mf,
  },
  {"code": "MG", "name": "Madagascar", "dial_code": "+261", "flag": AppFlag.mg},
  {
    "code": "MH",
    "name": "Marshall Islands",
    "dial_code": "+692",
    "flag": AppFlag.mh,
  },
  {
    "code": "MK",
    "name": "North Macedonia",
    "dial_code": "+389",
    "flag": AppFlag.mk,
  },
  {"code": "ML", "name": "Mali", "dial_code": "+223", "flag": AppFlag.ml},
  {"code": "MM", "name": "Myanmar", "dial_code": "+95", "flag": AppFlag.mm},
  {"code": "MN", "name": "Mongolia", "dial_code": "+976", "flag": AppFlag.mn},
  {"code": "MO", "name": "Macao", "dial_code": "+853", "flag": AppFlag.mo},
  {
    "code": "MP",
    "name": "Northern Mariana Islands",
    "dial_code": "+1-670",
    "flag": AppFlag.mp,
  },
  {"code": "MQ", "name": "Martinique", "dial_code": "+596", "flag": AppFlag.mq},
  {"code": "MR", "name": "Mauritania", "dial_code": "+222", "flag": AppFlag.mr},
  {
    "code": "MS",
    "name": "Montserrat",
    "dial_code": "+1-664",
    "flag": AppFlag.ms,
  },
  {"code": "MT", "name": "Malta", "dial_code": "+356", "flag": AppFlag.mt},
  {"code": "MU", "name": "Mauritius", "dial_code": "+230", "flag": AppFlag.mu},
  {"code": "MV", "name": "Maldives", "dial_code": "+960", "flag": AppFlag.mv},
  {"code": "MW", "name": "Malawi", "dial_code": "+265", "flag": AppFlag.mw},
  {"code": "MX", "name": "Mexico", "dial_code": "+52", "flag": AppFlag.mx},
  {"code": "MY", "name": "Malaysia", "dial_code": "+60", "flag": AppFlag.my},
  {"code": "MZ", "name": "Mozambique", "dial_code": "+258", "flag": AppFlag.mz},
  {"code": "NA", "name": "Namibia", "dial_code": "+264", "flag": AppFlag.na},
  {
    "code": "NC",
    "name": "New Caledonia",
    "dial_code": "+687",
    "flag": AppFlag.nc,
  },
  {"code": "NE", "name": "Niger", "dial_code": "+227", "flag": AppFlag.ne},
  {
    "code": "NF",
    "name": "Norfolk Island",
    "dial_code": "+672",
    "flag": AppFlag.nf,
  },
  {"code": "NG", "name": "Nigeria", "dial_code": "+234", "flag": AppFlag.ng},
  {"code": "NI", "name": "Nicaragua", "dial_code": "+505", "flag": AppFlag.ni},
  {"code": "NL", "name": "Netherlands", "dial_code": "+31", "flag": AppFlag.nl},
  {"code": "NO", "name": "Norway", "dial_code": "+47", "flag": AppFlag.no},
  {"code": "NP", "name": "Nepal", "dial_code": "+977", "flag": AppFlag.np},
  {"code": "NR", "name": "Nauru", "dial_code": "+674", "flag": AppFlag.nr},
  {"code": "NU", "name": "Niue", "dial_code": "+683", "flag": AppFlag.nu},
  {"code": "NZ", "name": "New Zealand", "dial_code": "+64", "flag": AppFlag.nz},
  {"code": "OM", "name": "Oman", "dial_code": "+968", "flag": AppFlag.om},
  {"code": "PA", "name": "Panama", "dial_code": "+507", "flag": AppFlag.pa},
  {"code": "PE", "name": "Peru", "dial_code": "+51", "flag": AppFlag.pe},
  {
    "code": "PF",
    "name": "French Polynesia",
    "dial_code": "+689",
    "flag": AppFlag.pf,
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "dial_code": "+675",
    "flag": AppFlag.pg,
  },
  {"code": "PH", "name": "Philippines", "dial_code": "+63", "flag": AppFlag.ph},
  {"code": "PK", "name": "Pakistan", "dial_code": "+92", "flag": AppFlag.pk},
  {"code": "PL", "name": "Poland", "dial_code": "+48", "flag": AppFlag.pl},
  {
    "code": "PM",
    "name": "Saint Pierre and Miquelon",
    "dial_code": "+508",
    "flag": AppFlag.pm,
  },
  {"code": "PN", "name": "Pitcairn", "dial_code": "+870", "flag": AppFlag.pn},
  {
    "code": "PR",
    "name": "Puerto Rico",
    "dial_code": "+1-787",
    "flag": AppFlag.pr,
  },
  {"code": "PS", "name": "Palestine", "dial_code": "+970", "flag": AppFlag.ps},
  {"code": "PT", "name": "Portugal", "dial_code": "+351", "flag": AppFlag.pt},
  {"code": "PW", "name": "Palau", "dial_code": "+680", "flag": AppFlag.pw},
  {"code": "PY", "name": "Paraguay", "dial_code": "+595", "flag": AppFlag.py},
  {"code": "QA", "name": "Qatar", "dial_code": "+974", "flag": AppFlag.qa},
  {"code": "RE", "name": "Réunion", "dial_code": "+262", "flag": AppFlag.re},
  {"code": "RO", "name": "Romania", "dial_code": "+40", "flag": AppFlag.ro},

  {"code": "RS", "name": "Serbia", "dial_code": "+381", 'flag': AppFlag.rs},
  {
    "code": "RU",
    "name": "Russian Federation",
    "dial_code": "+7",
    'flag': AppFlag.ru,
  },
  {"code": "RW", "name": "Rwanda", "dial_code": "+250", 'flag': AppFlag.rw},
  {
    "code": "SA",
    "name": "Saudi Arabia",
    "dial_code": "+966",
    'flag': AppFlag.sa,
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "dial_code": "+677",
    'flag': AppFlag.sb,
  },
  {"code": "SC", "name": "Seychelles", "dial_code": "+248", 'flag': AppFlag.sc},
  {"code": "SD", "name": "Sudan", "dial_code": "+249", 'flag': AppFlag.sd},
  {"code": "SE", "name": "Sweden", "dial_code": "+46", 'flag': AppFlag.se},
  {"code": "SG", "name": "Singapore", "dial_code": "+65", 'flag': AppFlag.sg},
  {
    "code": "SH",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "dial_code": "+290",
    'flag': AppFlag.sh,
  },
  {"code": "SI", "name": "Slovenia", "dial_code": "+386", 'flag': AppFlag.si},
  {
    "code": "SJ",
    "name": "Svalbard and Jan Mayen Islands",
    "dial_code": "+47",
    'flag': AppFlag.sj,
  },
  {"code": "SK", "name": "Slovakia", "dial_code": "+421", 'flag': AppFlag.sk},
  {
    "code": "SL",
    "name": "Sierra Leone",
    "dial_code": "+232",
    'flag': AppFlag.sl,
  },
  {"code": "SM", "name": "San Marino", "dial_code": "+378", 'flag': AppFlag.sm},
  {"code": "SN", "name": "Senegal", "dial_code": "+221", 'flag': AppFlag.sn},
  {"code": "SO", "name": "Somalia", "dial_code": "+252", 'flag': AppFlag.so},
  {"code": "SR", "name": "Suriname", "dial_code": "+597", 'flag': AppFlag.sr},
  {
    "code": "SS",
    "name": "South Sudan",
    "dial_code": "+211",
    'flag': AppFlag.ss,
  },
  {
    "code": "ST",
    "name": "Sao Tome and Principe",
    "dial_code": "+239",
    'flag': AppFlag.st,
  },
  {
    "code": "SV",
    "name": "El Salvador",
    "dial_code": "+503",
    'flag': AppFlag.sv,
  },
  {
    "code": "SX",
    "name": "Sint Maarten (Dutch part)",
    "dial_code": "+1-721",
    'flag': AppFlag.sx,
  },
  {
    "code": "SY",
    "name": "Syrian Arab Republic",
    "dial_code": "+963",
    'flag': AppFlag.sy,
  },
  {
    "code": "SZ",
    "name": "Kingdom of Eswatini",
    "dial_code": "+268",
    'flag': AppFlag.sz,
  },
  {
    "code": "TC",
    "name": "Turks and Caicos Islands",
    "dial_code": "+1-649",
    'flag': AppFlag.tc,
  },
  {"code": "TD", "name": "Chad", "dial_code": "+235", 'flag': AppFlag.td},
  {
    "code": "TF",
    "name": "French Southern Territories",
    "dial_code": "+262",
    'flag': AppFlag.tf,
  },
  {"code": "TG", "name": "Togo", "dial_code": "+228", 'flag': AppFlag.tg},
  {"code": "TH", "name": "Thailand", "dial_code": "+66", 'flag': AppFlag.th},
  {"code": "TJ", "name": "Tajikistan", "dial_code": "+992", 'flag': AppFlag.tj},
  {"code": "TK", "name": "Tokelau", "dial_code": "+690", 'flag': AppFlag.tk},
  {
    "code": "TL",
    "name": "Timor-Leste",
    "dial_code": "+670",
    'flag': AppFlag.tl,
  },
  {
    "code": "TM",
    "name": "Turkmenistan",
    "dial_code": "+993",
    'flag': AppFlag.tm,
  },
  {"code": "TN", "name": "Tunisia", "dial_code": "+216", 'flag': AppFlag.tn},
  {"code": "TO", "name": "Tonga", "dial_code": "+676", 'flag': AppFlag.to},
  {
    "code": "TR",
    "name": "Republic of Türkiye",
    "dial_code": "+90",
    'flag': AppFlag.tr,
  },
  {
    "code": "TT",
    "name": "Trinidad and Tobago",
    "dial_code": "+1-868",
    'flag': AppFlag.tt,
  },
  {"code": "TV", "name": "Tuvalu", "dial_code": "+688", 'flag': AppFlag.tv},
  {
    "code": "TW",
    "name": "Taiwan (Republic of China)",
    "dial_code": "+886",
    'flag': AppFlag.tw,
  },
  {
    "code": "TZ",
    "name": "Tanzania, United Republic of",
    "dial_code": "+255",
    'flag': AppFlag.tz,
  },
  {"code": "UA", "name": "Ukraine", "dial_code": "+380", 'flag': AppFlag.ua},
  {"code": "UG", "name": "Uganda", "dial_code": "+256", 'flag': AppFlag.ug},
  {
    "code": "UM",
    "name": "US Minor Outlying Islands",
    "dial_code": "+1",
    'flag': AppFlag.um,
  },
  {
    "code": "US",
    "name": "United States",
    "dial_code": "+1",
    'flag': AppFlag.us,
  },
  {"code": "UY", "name": "Uruguay", "dial_code": "+598", 'flag': AppFlag.uy},
  {"code": "UZ", "name": "Uzbekistan", "dial_code": "+998", 'flag': AppFlag.uz},
  {
    "code": "VA",
    "name": "Holy See (Vatican City State)",
    "dial_code": "+379",
    'flag': AppFlag.va,
  },
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "dial_code": "+1-784",

    'flag': AppFlag.vc,
  },
  {
    "code": "VE",
    "name": "Venezuela, Bolivarian Republic of",
    "dial_code": "+58",
    'flag': AppFlag.ve,
  },
  {
    "code": "VG",
    "name": "Virgin Islands, British",
    "dial_code": "+1-284",
    'flag': AppFlag.vg,
  },
  {
    "code": "VI",
    "name": "Virgin Islands, U.S.",
    "dial_code": "+1-340",
    'flag': AppFlag.vi,
  },
  {"code": "VN", "name": "Vietnam", "dial_code": "+84", 'flag': AppFlag.vn},
  {"code": "VU", "name": "Vanuatu", "dial_code": "+678", 'flag': AppFlag.vu},
  {
    "code": "WF",
    "name": "Wallis and Futuna Islands",
    "dial_code": "+681",
    'flag': AppFlag.wf,
  },
  {"code": "WS", "name": "Samoa", "dial_code": "+685", 'flag': AppFlag.ws},
  {"code": "XK", "name": "Kosovo", "dial_code": "+383", 'flag': AppFlag.xk},
  {"code": "YE", "name": "Yemen", "dial_code": "+967", 'flag': AppFlag.ye},
  {"code": "YT", "name": "Mayotte", "dial_code": "+262", 'flag': AppFlag.yt},
  {
    "code": "ZA",
    "name": "South Africa",
    "dial_code": "+27",
    'flag': AppFlag.za,
  },
  {"code": "ZM", "name": "Zambia", "dial_code": "+260", 'flag': AppFlag.zm},
  {"code": "ZW", "name": "Zimbabwe", "dial_code": "+263", 'flag': AppFlag.zw},
];
