// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIlsu1smhI3JEL-XWZKanLBvRyYuR1MtI',
    appId: '1:927629152845:web:dccd8e2bc3b90b8dea0204',
    messagingSenderId: '927629152845',
    projectId: 'shishu-sanskar',
    authDomain: 'shishu-sanskar.firebaseapp.com',
    storageBucket: 'shishu-sanskar.firebasestorage.app',
    measurementId: 'G-PXFM1THM3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJjqc25p-ceV-sb3IBpQJuFfFBSiX1Ms',
    appId: '1:927629152845:android:33112dbb84a84944ea0204',
    messagingSenderId: '927629152845',
    projectId: 'shishu-sanskar',
    storageBucket: 'shishu-sanskar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVqSy8o1V2PiOMCy63ydpDcNMQz7_KdA',
    appId: '1:927629152845:ios:374870e74b511cbdea0204',
    messagingSenderId: '927629152845',
    projectId: 'shishu-sanskar',
    storageBucket: 'shishu-sanskar.firebasestorage.app',
    iosBundleId: 'com.example.shishuSanskar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWVqSy8o1V2PiOMCy63ydpDcNMQz7_KdA',
    appId: '1:927629152845:ios:374870e74b511cbdea0204',
    messagingSenderId: '927629152845',
    projectId: 'shishu-sanskar',
    storageBucket: 'shishu-sanskar.firebasestorage.app',
    iosBundleId: 'com.example.shishuSanskar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIlsu1smhI3JEL-XWZKanLBvRyYuR1MtI',
    appId: '1:927629152845:web:c0b3c1167d6e3ec5ea0204',
    messagingSenderId: '927629152845',
    projectId: 'shishu-sanskar',
    authDomain: 'shishu-sanskar.firebaseapp.com',
    storageBucket: 'shishu-sanskar.firebasestorage.app',
    measurementId: 'G-X1MTVSC2T6',
  );
}
