// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsDkd7RwTUiFn7YtwdiSNm_Exdw9PCV0',
    appId: '1:392298455531:web:ba3d1fab736edb7756f9ae',
    messagingSenderId: '392298455531',
    projectId: 'shishu-sanskar-app',
    authDomain: 'shishu-sanskar-app.firebaseapp.com',
    storageBucket: 'shishu-sanskar-app.firebasestorage.app',
    measurementId: 'G-KF8CF8E2B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqWSNqzgtRfQuEEiAy4Q9eQXTK1CakNc',
    appId: '1:392298455531:android:7c7a56e09418bf3e56f9ae',
    messagingSenderId: '392298455531',
    projectId: 'shishu-sanskar-app',
    storageBucket: 'shishu-sanskar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPUBSDzHDyNVZc0U0lJdbjiwFvWICdIZw',
    appId: '1:392298455531:ios:dd23ab48327d225456f9ae',
    messagingSenderId: '392298455531',
    projectId: 'shishu-sanskar-app',
    storageBucket: 'shishu-sanskar-app.firebasestorage.app',
    iosBundleId: 'com.example.shishuSanskar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPUBSDzHDyNVZc0U0lJdbjiwFvWICdIZw',
    appId: '1:392298455531:ios:dd23ab48327d225456f9ae',
    messagingSenderId: '392298455531',
    projectId: 'shishu-sanskar-app',
    storageBucket: 'shishu-sanskar-app.firebasestorage.app',
    iosBundleId: 'com.example.shishuSanskar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYsDkd7RwTUiFn7YtwdiSNm_Exdw9PCV0',
    appId: '1:392298455531:web:1cbebe671683e3ee56f9ae',
    messagingSenderId: '392298455531',
    projectId: 'shishu-sanskar-app',
    authDomain: 'shishu-sanskar-app.firebaseapp.com',
    storageBucket: 'shishu-sanskar-app.firebasestorage.app',
    measurementId: 'G-XY4T83EQBQ',
  );
}
