// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdxITf2KApo2duKjrd99m0IBsjROGCI0',
    appId: '1:347680811790:web:96c6ddf3ade1263152055f',
    messagingSenderId: '347680811790',
    projectId: 'shishu-sanskar-7a4e6',
    authDomain: 'shishu-sanskar-7a4e6.firebaseapp.com',
    storageBucket: 'shishu-sanskar-7a4e6.firebasestorage.app',
    measurementId: 'G-YN75MQJR1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZYMyncnvDt4UCnXHj_c4POysmoQItAQ',
    appId: '1:347680811790:android:02cf082025c20f7a52055f',
    messagingSenderId: '347680811790',
    projectId: 'shishu-sanskar-7a4e6',
    storageBucket: 'shishu-sanskar-7a4e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6R1GEjSfyWvPPgjntFCAGRgL5t5ayueE',
    appId: '1:347680811790:ios:4a64072824c74b4b52055f',
    messagingSenderId: '347680811790',
    projectId: 'shishu-sanskar-7a4e6',
    storageBucket: 'shishu-sanskar-7a4e6.firebasestorage.app',
    iosBundleId: 'com.example.shishuSanskar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6R1GEjSfyWvPPgjntFCAGRgL5t5ayueE',
    appId: '1:347680811790:ios:4a64072824c74b4b52055f',
    messagingSenderId: '347680811790',
    projectId: 'shishu-sanskar-7a4e6',
    storageBucket: 'shishu-sanskar-7a4e6.firebasestorage.app',
    iosBundleId: 'com.example.shishuSanskar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkdxITf2KApo2duKjrd99m0IBsjROGCI0',
    appId: '1:347680811790:web:4c2d93c82ba9775652055f',
    messagingSenderId: '347680811790',
    projectId: 'shishu-sanskar-7a4e6',
    authDomain: 'shishu-sanskar-7a4e6.firebaseapp.com',
    storageBucket: 'shishu-sanskar-7a4e6.firebasestorage.app',
    measurementId: 'G-KTJZ4PJ0EQ',
  );
}
